version: '3.9'

services:
  valemilk-web:
    build: .
    container_name: valemilk_app
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: always
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - COMPRESS_LEVEL=${COMPRESS_LEVEL:-6}
